### ISSUE TITLE
Can't find Titanfall 2 sound: tone_dlc_execution_part_01.

### ISSUE THREAD

**Issue by begin-theadventure** [r-ex/LegionPlus#117]
Hello, there's a sound that's part 1 of Tone's Prime execution that can't be found.
Other parts can be found, but not this one.
This sound can be played in-game with: `script_ui EmitUISound("tone_dlc_execution_part_01")`.

**Comment by biast12** [comment]
tone_execution_part_01 :/

**Comment by IJARika** [comment]
scripts play sound events, which are not source files (what legion exports). events can use more than one source, can't really help you with finding them unfortunately.
