### ISSUE TITLE
Apex Legion Problem with load files

### ISSUE THREAD

**Issue by gzreaperz** [r-ex/LegionPlus#118]
There is a problem with finding the legendary/epic skins of apex legends that I don't know how to solve, it's as if it loaded fewer files than it should, if anyone knows how to solve this problem it would be greatly appreciated
![apex error](https://github.com/r-ex/LegionPlus/assets/133743204/11816b3a-dbf7-458f-9560-f7959de958c9)

**Comment by IJARika** [comment]
load common.rpak and root_lgnd_skins.rpak
