### ISSUE TITLE
Previewing some legendary character models causes a crash

### ISSUE THREAD

**Issue by leadguitar1990** [r-ex/LegionPlus#122]
For Apex Legends game files, specifically root_lgnd_skins.rpak. When I press "P" to preview a character model the app often crashes. This occurs for pilot and non pilot models. 

 The problem seems to come from specific models.

There is no problem with exporting these characters.

Switching to version 1.6.1 improves the issue, but it still occurs occasionally.

**Comment by floxay** [comment]
You have to load `common.rpak` along with `root_lgnd_skins.rpak`.
You probably also want to load the patch rpaks for these, eg.; `common(01).rpak`, `common(02).rpak`, `root_lgnd_skins(01).rpak`, and so on.
