### ISSUE TITLE
[Titanfall 2 DDS] Allow exporting in sRGB

### ISSUE THREAD

**Issue by begin-theadventure** [r-ex/LegionPlus#124]
Images (e.g. PNG) are darker when exported, this is because DDS images use the sRGB standard.

Tacentview, for example, has an option to change DDS to sRGB, which produces correctly bright images when exported to other formats.

**Comment by IJARika** [comment]
Legion exports DDS files as SRGB(DX10 formats). I've also just checked, and the PNGs look fine, this was an issue fixed a while back by Floxay I believe.

**Comment by begin-theadventure** [comment]
I'm using 1.7.0+3de60f3. Maybe extracting images with gamma correction applied is what I actually mean?

**Comment by IJARika** [comment]
Does this only happen when trying to export ui images?

**Comment by begin-theadventure** [comment]
I exported `Image v8 calling_card` as PNG and everything is fine.
The banner in it looks the same as the second image I sent.

**Comment by IJARika** [comment]
Sick, but I was asking if this only happened when exporting the UI Image Atlas asset. I know there's nothing wrong with the base texture, pretty sure I found the spot that is causing issues as well.

**Comment by IJARika** [comment]
should be fixed with commit dcf475e

**Comment by begin-theadventure** [comment]
Great.
