### ISSUE TITLE
Error while exporting audio files (titanfall2)

### ISSUE THREAD

**Issue by Fabbbr0** [r-ex/LegionPlus#130]
if i want to export an audio file (Example diag_sp_anderson_TS171_12_02_mcor_bt_L2) it gives me an error and dosent export anything.
there is nothing in the log file

**Comment by biast12** [comment]
this can be a few things, Legion+ does not support non ascii characters so make sure all your characters in your path isn't that

it can also be that you don't have binkawin64.dll and mileswin64.dll in the same dir as Legion+, you can get those files in your "<Titanfall 2>\bin\x64_retail" path, tho i do think it's the first option

**Comment by Fabbbr0** [comment]
> this can be a few things, Legion+ does not support non ascii characters so make sure all your characters in your path isn't that
> 
> it can also be that you don't have binkawin64.dll and mileswin64.dll in the same dir as Legion+, you can get those files in your "<Titanfall 2>\bin\x64_retail" path

i replaced those files and it still dosen't work.
I can export only some audio files not all of them.
so maybe its the fist thing you said how do i do that?

**Comment by biast12** [comment]
i can't find `diag_sp_anderson_TS171_12_02_mcor_bt_L2`, do you mean `diag_sp_anderson_TS171_12_01_mcor_bt_L2`, becuse that works for me

can you show me your settings and the full Path Legion+ is in?

**Comment by biast12** [comment]
Try adding these in the same path as Legion+
[binkawin64.zip](https://github.com/r-ex/LegionPlus/files/12641494/binkawin64.zip)

**Comment by Fabbbr0** [comment]
> i can't find `diag_sp_anderson_TS171_12_02_mcor_bt_L2`, do you mean `diag_sp_anderson_TS171_12_01_mcor_bt_L2`, because that works for me
> 
> can you show me your settings and the full Path Legion+ is in?

the Legion+ Path is "C:\Users\Pc\Desktop\Legion+1.7.0"

by settings you mean this right?
![image](https://github.com/r-ex/LegionPlus/assets/109289253/121f2fe0-8e76-4ccd-ab07-468baa28186c)

**Comment by Fabbbr0** [comment]
OMG i fixed it, i didn't selected the language i had the game in (italian) now it works for every voiceline
