### ISSUE TITLE
Opening updated Apex UPHEAVAL .rpak crashes Legion Plus

### ISSUE THREAD

**Issue by Stifler9000** [r-ex/LegionPlus#145]
Hello!

Opening `mp_rr_canyonlands_hu.rpak` with Legion Plus for example causes Legion Plus to crash since the game update.
Any chance this could get looked into?

Thanks!

**Comment by Stifler9000** [comment]
On closer inspection, the pak header doesn't seem to have changed substantially but extraction fails

**Comment by bunnitooo** [comment]
It opens normally for me, but when I go to load the files it closes without showing me any errors

**Comment by endermyne** [comment]
Idk if its helpful but certain random files can still load fine, such as root_lgnd_skins_bangalore_lgnd_v21_warlord_rt01.rpak and some files that don't contain models, files that seem like they would have models like charms and such don't load (may also have nothing to do with that and i'm just getting lucky)

**Comment by Ashyslashy2000** [comment]
I just tried to export Alter's pilot model and the program is crashing :/ Any update as to when there will be a patch for season 21?

**Comment by biast12** [comment]
Hey everyone, Legion+ likely won't get fixed (unless someone wanna fix it), the legion+ devs are working on a new tool that's gonna replace legion+, the tool should be released within today or tomorrow (hopefully), so do be patient for now

If you guys need files from a previous Apex update then you can find the files in my archive for now: [https://biast12.site](https://biast12.site)
Have a nice day 😊

**Comment by bunnitooo** [comment]
@biast12 How i can dowload your archives?

**Comment by mrsteyk** [comment]
> On closer inspection, the pak header doesn't seem to have changed substantially but decompression fails. IsCompressed is set to 2 instead of 1 and the actual data starts after 8 bytes (with those 8 bytes being all 0) after the header as opposed to 16. So this is probably a different compression algorithm

That "IsCompressed" is incorrect, they actually have 16-bit flag field, it just so happened that compressed flag was there. Respawn reworked their stuff and put all their rework into 0x200 flag: oodle lz compression using Leviathan (13) and signature check.

**Comment by biast12** [comment]
> @biast12 How i can download your archives?

Just go to the folder you wanna download, select the things you wanna download and click the download button at the left corner, i don't recommend you trying to download everything btw, just those you need for now

Also the new tool has gotten released (https://github.com/r-ex/rsx/releases/tag/1.0.0) so i would rather recommend you using that unless someone wanna fix legion+

**Comment by bunnitooo** [comment]
@biast12 I need a tutorial to load a model in Blender xD sorry i recent start making thumbnails in Blender
