### ISSUE TITLE
a LOTS of TTF2 audio assets can't be extracted

### ISSUE THREAD

**Issue by L0891-3BDBFF** [r-ex/LegionPlus#151]
only 17371 files are extracted in all 34402 assets in general.mbnk, other's status are error and can't be extract with all versions of LEGION or LEGION+

the quality of extracted audio seems pretty good tho

**Comment by SoulGI** [comment]
Please select correct "Audio Language" in Legion+ Settings. If your "Audio Language" does not match the "Game Language", the export will fail.

**Comment by L0891-3BDBFF** [comment]
> Please select correct "Audio Language" in Legion+ Settings. If your "Audio Language" does not match the "Game Language", the export will fail.

oh sorry, never mentioned that before

**Comment by L0891-3BDBFF** [comment]
> Please select correct "Audio Language" in Legion+ Settings. If your "Audio Language" does not match the "Game Language", the export will fail.

oh sorry, didn't notice that before
it's working fine now
