### ISSUE TITLE
Legion appears to crash when converting specific TF|2 .mdl files to .semodel or .cast

### ISSUE THREAD

**Issue by Codebreakerblue** [r-ex/LegionPlus#18]
Legion version 1.3.6
.mdl exported using Titanfall VPK tool 3.4
Northstar is installed if that matters?

When I drag and drop a .mdl file into the legion window, legion creates the exported_files folder and the correct folders inside it, but closes without exporting anything. Weirdly, this only happens with certain .mdl files. Some behave as expected. Might have something to do with animations or bones? The .log files are empty.

**Failed with:** pilot_medium_reaper_f, pilot_light_ged_f, pilot_light_ged_m, r2_prowler
Bizarrely, **succeeded with:** pelican_case_large_open, terminal_usable_imc_01, core_energy

Thanks!

**Comment by IJARika** [comment]
it should be functional as soon as #101 is merged, with improved functionality over normal legion.

**Comment by Codebreakerblue** [comment]
Incredible 😄

**Comment by r-ex** [comment]
resolved in #101
