### ISSUE TITLE
Crash when exporting certain atlases, and some images are not exported correctly (Titanfall 2)

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [r-ex/LegionPlus#20]
I'm having this be one issue instead of two because I believe the second one is the root cause of the first.

In ui(11).rpak, "menu" (alongside some other images) does not get exported properly. When exporting to png, the result is just a grey/black blank image. Whereas when exporting to dds, I get an error when importing the file into gimp.

Legionplus also crashes when attempting to export the corresponding atlases to the images that do not export properly

**Comment by biast12** [comment]
i get this when exporting the atlas_0x5b309baef5f751a3 atlas ![image](https://user-images.githubusercontent.com/53872542/174479413-cb1100ab-d5eb-469f-8947-ccc0bab9dd53.png)

**Comment by r-ex** [comment]
this is most likely a patching issue
