### ISSUE TITLE
How to find season 13 cosmetics???

### ISSUE THREAD

**Issue by nighthawk333** [r-ex/LegionPlus#21]
I cant seem to find the new skins for Season 13 Battlepass? what am i missing?

**Comment by biast12** [comment]
Download the latest version of Legion+

**Comment by biast12** [comment]
they're in there, you just gotta look, also this isn't a Legion+ issue

**Comment by nighthawk333** [comment]
Ive gone through everything and cant seem to find the Seer power ranger type one :/ Any idea on what file? can't see in Common.rpak :(

**Comment by r-ex** [comment]
it'll be in common(01).rpak

**Comment by nighthawk333** [comment]
Thanks just found it. For anyone else, quick search - herohunter_w

**Comment by Lykan5566** [comment]
When I preview the hero hunter, it falls.

**Comment by r-ex** [comment]
> When I preview the hero hunter, it falls.

get the latest release at https://github.com/r-ex/LegionPlus/releases/latest

**Comment by Lykan5566** [comment]
Thanks!
