### ISSUE TITLE
error when exporting french audio

### ISSUE THREAD

**Issue by gregprojects** [r-ex/LegionPlus#23]
Running legion plus on a windows 10 qemu vm. I'm trying to extract all of northstars french voice lines. Legion+ is throwing an error with most all of the files.
![image](https://user-images.githubusercontent.com/54902309/177685842-c676fb60-4b8a-4398-b30c-4d11f131457c.png)
I'm going to have a friend on native windows try and see but opening an issue for now. Nothing in the log file, only export success messages.

**Comment by gregprojects** [comment]
Here is the log if that also helps.
[](url
[2022-07-06.log](https://github.com/r-ex/LegionPlus/files/9060228/2022-07-06.log)
)

**Comment by biast12** [comment]
Legion+ doesn't work with other languages on Tf2, it only works on Apex rn

**Comment by gregprojects** [comment]
OK, thanks for letting me know. Are there any plans to implement other languages for tf2 in the future?

**Comment by biast12** [comment]
tbh i would be surprised if anyone is gonna work on Legion+ anymore other than fixes

**Comment by zxcPandora** [comment]
you should use `MSD` to dump tf2 audio
Here's my repository:https://github.com/zxcPandora/Titanfall-2-Audio-Dumper

**Comment by r-ex** [comment]
should be fixed in 7387de66887cf541edf8e69482060f43f68909f3

**Comment by zxcPandora** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在百度贴吧潜水中，无法亲自回复您的邮件。我将在百度贴吧潜水结束后，尽快给您回复。
