### ISSUE TITLE
Crashing when trying to export Gaiden event skins

### ISSUE THREAD

**Issue by SweetPeaP** [r-ex/LegionPlus#27]
[Apex Legends]. Legion+ App repeatedly crashes when trying to export legend models for the current Gaiden event. Export does not happen and CPU usage skyrockets. Never had this issue and my CPU is an 11th gen i7.

**Comment by SweetPeaP** [comment]
No I wasn't but will update it now and will let you know if the issue persists. Thanks

**Comment by SweetPeaP** [comment]
Issue isn't present on the new update. Thanks again

**Comment by biast12** [comment]
we really need to add the auto updater at some point
