### ISSUE TITLE
add timestamp check to new v14 model fix

### ISSUE THREAD

**Issue by r-ex** [r-ex/LegionPlus#32]
need to implement a check for the rpak's build time to allow backwards compatibility with 13.1 mdl v14, as there are some breaking changes in 14.0

**Comment by IcePixelx** [comment]
Doesn't seem to be necessary after testing models for awhile.
They look fine but might be broken when imported in blender and such which I can't test.

**Comment by IcePixelx** [comment]
Closed for now, doesn't seem to be needed.
