### ISSUE TITLE
Full Asset Path Setting breaks BSP Exporting

### ISSUE THREAD

**Issue by IcePixelx** [r-ex/LegionPlus#40]
Just turn it off when ExportBsp gets called.

**Comment by biast12** [comment]
"Fixed" in this [pull request#41](https://github.com/r-ex/LegionPlus/pull/41)

**Comment by biast12** [comment]
Fixed in this [Pull Request#41](https://github.com/r-ex/LegionPlus/pull/41)

**Comment by biast12** [comment]
We can close this, the fix is pushed
