### ISSUE TITLE
Error when exporting diag_mcor_marvin sounds from Titanfall 2

### ISSUE THREAD

**Issue by begin-theadventure** [r-ex/LegionPlus#46]
diag_mcor_marvin & Marvin_Vocal.
Error when exporting Marvin's audio.
The original Legion exports it but the audio is empty.
Could it be because the same audio is used for all languages?

**Comment by biast12** [comment]
you need the dll files from titanfall 2 to export titanfall 2 sounds

**Comment by begin-theadventure** [comment]
> you need the dll files from titanfall 2 to export titanfall 2 sounds

I don't understand your reply..

**Comment by biast12** [comment]
you're trying to export titanfall 2 sounds right? yeah you need the binkawin64.dll and mileswin64.dll file for titanfall 2 to export the sounds

**Comment by begin-theadventure** [comment]
> 

I need Legion Plus.

**Comment by r-ex** [comment]
> you're trying to export titanfall 2 sounds right? yeah you need the binkawin64.dll and mileswin64.dll file for titanfall 2 to export the sounds

no, the dlls in the release should work for tf2. also that isn't even the issue

**Comment by biast12** [comment]
> > you're trying to export titanfall 2 sounds right? yeah you need the binkawin64.dll and mileswin64.dll file for titanfall 2 to export the sounds
> 
> no, the dlls in the release should work for tf2. also that isn't even the issue. the error is in legionplus code, not binka code

oh, well my bad then

**Comment by begin-theadventure** [comment]
There's more. Legion+ also can't export Frontier Defense sounds (FrontierDefense, cmdr_), while Legion can.

**Comment by r-ex** [comment]
fixed in 75363a03565674414380f145cc4c1a90eb8c2eba. issue was caused by an arbitrary check added by d0e1b8e11228e984acbc5210b9fb004ae13c5bc0 (#7), in which all patch streams would be discarded instead of being added to the streaming file list

**Comment by begin-theadventure** [comment]
Thanks!
