### ISSUE TITLE
Incorrectly extracted texture data

### ISSUE THREAD

**Issue by floxay** [r-ex/LegionPlus#55]
Some textures are extracted incorrectly and they include unrelated or lower mip data.

Examples:
0xc26aaaff2b114147
![image](https://user-images.githubusercontent.com/57007485/188702870-e90ac3fc-828b-4246-b367-cd86b4e26d0c.png)
0x286021c5564b1baa
![image](https://user-images.githubusercontent.com/57007485/188702791-f99f0cc1-36b3-4aac-81bb-ad5e6dc2365b.png)
0xdaf40aa1287fb99b
![image](https://user-images.githubusercontent.com/57007485/188702691-679dd2c9-8ca2-4b2e-b1e5-c2731cca8e62.png)

**Comment by IcePixelx** [comment]
Will check, I think I was aware of that issue and forgot about it though. It's kinda weird.

**Comment by r-ex** [comment]
iirc textures that only exist in the rpak have their mip order flipped compared to streaming textures

**Comment by IcePixelx** [comment]
#76

**Comment by IcePixelx** [comment]
Fixed with 17a5969f3d5a74b81f6b41924b8dc644982a9204
