### ISSUE TITLE
Catalyst Victim finishers are nowhere to be found.

### ISSUE THREAD

**Issue by Falc47** [r-ex/LegionPlus#82]
Can't find catalyst victim finisher animations in apex legion.

**Comment by biast12** [comment]
They're in mp_pilot_light_core, mp_pilot_medium_core and mp_pilot_heavy_core like all victim finishers are

**Comment by Falc47** [comment]
there not there i don't see catalyst name appaer as victim.

**Comment by biast12** [comment]
medium_catalyst_execution_crusher_0
medium_catalyst_execution_choking_0
both in mp_pilot_medium_core
change the medium at the start to what size folder you're using
