### ISSUE TITLE
Every thing is broken now?

### ISSUE THREAD

**Issue by Goldermor** [r-ex/LegionPlus#92]
I checked with a friend, he has the same thing
![image](https://user-images.githubusercontent.com/77431249/201812006-01d750e0-1ef3-4dd8-8c6e-da1c8a8d26ef.png)
![image](https://user-images.githubusercontent.com/77431249/201812207-7c889aeb-9784-42d1-ba72-ddd26ffe28c4.png)

**Comment by r-ex** [comment]
you are using an old build of legionplus. get the latest at https://github.com/r-ex/LegionPlus/releases/tag/1.5.0

**Comment by Goldermor** [comment]
I swear to god, I haven't seen the latest release
1.4.3 was the last one for me 0-0
Am I really that blind
